# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-FITS-HdrTrans
version:      0.04
version_from: lib/Astro/FITS/HdrTrans.pm
installdirs:  site
requires:
    Math::Trig:                    0
    Switch:                        0
    Test::More:                    0
    Time::Piece:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
