--- #YAML:1.0
name:               Astro-FITS-HdrTrans
version:            1.50
abstract:           Translate FITS headers to standardised form
author:
    - Brad Cavanagh E<lt>b.cavanagh@jach.hawaii.eduE<gt>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Astro::Coords:        0
    Astro::FITS::Header:  0
    Astro::SLA:           0
    Astro::Telescope:     0
    DateTime:             0
    DateTime::TimeZone:   0
    Math::Trig:           0
    Scalar::Util:         0
    Switch:               0
    Test::More:           0
    Time::Piece:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
