---
abstract: 'Translate FITS headers to standardised form'
author:
  - 'Tim Jenness <t.jenness@jach.hawaii.edu>'
  - 'Brad Cavanagh <b.cavanagh@jach.hawaii.edu>'
build_requires:
  Test::More: 0
  Time::Piece: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Astro-FITS-HdrTrans
provides:
  Astro::FITS::HdrTrans:
    file: lib/Astro/FITS/HdrTrans.pm
    version: 1.50
  Astro::FITS::HdrTrans::ACSIS:
    file: lib/Astro/FITS/HdrTrans/ACSIS.pm
    version: 1.50
  Astro::FITS::HdrTrans::Base:
    file: lib/Astro/FITS/HdrTrans/Base.pm
    version: 1.50
  Astro::FITS::HdrTrans::CGS4New:
    file: lib/Astro/FITS/HdrTrans/CGS4New.pm
    version: 1.50
  Astro::FITS::HdrTrans::CGS4Old:
    file: lib/Astro/FITS/HdrTrans/CGS4Old.pm
    version: 1.50
  Astro::FITS::HdrTrans::CURVE:
    file: lib/Astro/FITS/HdrTrans/CURVE.pm
    version: 1.50
  Astro::FITS::HdrTrans::ClassicCam:
    file: lib/Astro/FITS/HdrTrans/ClassicCam.pm
    version: 1.50
  Astro::FITS::HdrTrans::ESO:
    file: lib/Astro/FITS/HdrTrans/ESO.pm
    version: 1.50
  Astro::FITS::HdrTrans::FITS:
    file: lib/Astro/FITS/HdrTrans/FITS.pm
    version: 1.50
  Astro::FITS::HdrTrans::GEMINI:
    file: lib/Astro/FITS/HdrTrans/GEMINI.pm
    version: 1.50
  Astro::FITS::HdrTrans::GMOS:
    file: lib/Astro/FITS/HdrTrans/GMOS.pm
    version: 1.50
  Astro::FITS::HdrTrans::INGRID:
    file: lib/Astro/FITS/HdrTrans/INGRID.pm
    version: 1.50
  Astro::FITS::HdrTrans::IRCAM:
    file: lib/Astro/FITS/HdrTrans/IRCAM.pm
    version: 1.50
  Astro::FITS::HdrTrans::IRIS2:
    file: lib/Astro/FITS/HdrTrans/IRIS2.pm
    version: 1.50
  Astro::FITS::HdrTrans::ISAAC:
    file: lib/Astro/FITS/HdrTrans/ISAAC.pm
    version: 1.50
  Astro::FITS::HdrTrans::JAC:
    file: lib/Astro/FITS/HdrTrans/JAC.pm
    version: 1.50
  Astro::FITS::HdrTrans::JCMT:
    file: lib/Astro/FITS/HdrTrans/JCMT.pm
  Astro::FITS::HdrTrans::JCMT_GSD:
    file: lib/Astro/FITS/HdrTrans/JCMT_GSD.pm
    version: 1.50
  Astro::FITS::HdrTrans::JCMT_GSD_DB:
    file: lib/Astro/FITS/HdrTrans/JCMT_GSD_DB.pm
    version: 1.50
  Astro::FITS::HdrTrans::MICHELLE:
    file: lib/Astro/FITS/HdrTrans/MICHELLE.pm
    version: 1.50
  Astro::FITS::HdrTrans::NACO:
    file: lib/Astro/FITS/HdrTrans/NACO.pm
    version: 1.50
  Astro::FITS::HdrTrans::NIRI:
    file: lib/Astro/FITS/HdrTrans/NIRI.pm
    version: 1.50
  Astro::FITS::HdrTrans::SCUBA:
    file: lib/Astro/FITS/HdrTrans/SCUBA.pm
    version: 1.50
  Astro::FITS::HdrTrans::SCUBA2:
    file: lib/Astro/FITS/HdrTrans/SCUBA2.pm
    version: 1.50
  Astro::FITS::HdrTrans::SOFI:
    file: lib/Astro/FITS/HdrTrans/SOFI.pm
    version: 1.50
  Astro::FITS::HdrTrans::SPEX:
    file: lib/Astro/FITS/HdrTrans/SPEX.pm
    version: 1.50
  Astro::FITS::HdrTrans::UFTI:
    file: lib/Astro/FITS/HdrTrans/UFTI.pm
    version: 1.50
  Astro::FITS::HdrTrans::UIST:
    file: lib/Astro/FITS/HdrTrans/UIST.pm
    version: 1.50
  Astro::FITS::HdrTrans::UKIRT:
    file: lib/Astro/FITS/HdrTrans/UKIRT.pm
    version: 1.50
  Astro::FITS::HdrTrans::UKIRTDB:
    file: lib/Astro/FITS/HdrTrans/UKIRTDB.pm
    version: 1.50
  Astro::FITS::HdrTrans::UKIRTNew:
    file: lib/Astro/FITS/HdrTrans/UKIRTNew.pm
    version: 1.50
  Astro::FITS::HdrTrans::UKIRTOld:
    file: lib/Astro/FITS/HdrTrans/UKIRTOld.pm
    version: 1.50
  Astro::FITS::HdrTrans::WFCAM:
    file: lib/Astro/FITS/HdrTrans/WFCAM.pm
    version: 1.50
recommends:
  Starlink::AST: 0
requires:
  Astro::Coords: 0
  Astro::FITS::Header: 0
  Astro::SLA: 0
  Astro::Telescope: 0
  DateTime: 0
  DateTime::TimeZone: 0
  Math::Trig: 0
  Scalar::Util: 0
  Time::Piece: 1.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/bradcavanagh/perl-Astro-FITS-HdrTrans.git
version: 1.51
